// <auto-generated />
using System;
using Emaktab.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Emaktab.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260618100622_UpdateModel")]
    partial class UpdateModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Emaktab.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateOnly>("CreateDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("LanguageType")
                        .HasColumnType("integer");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<int>("create_userId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("create_userId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Emaktab.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MaxScore")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Emaktab.Models.Document100", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("status_id")
                        .HasColumnType("integer");

                    b.Property<DateTime>("upload_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("user_id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("user_id");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Emaktab.Models.IshReja", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<string>("FanNomi")
                        .HasColumnType("text");

                    b.Property<string>("Guruh")
                        .HasColumnType("text");

                    b.Property<string>("Nomi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Sana")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tavsif")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("IshRejalar");
                });

            modelBuilder.Entity("Emaktab.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconPath")
                        .HasColumnType("text");

                    b.Property<long>("Pasport_number")
                        .HasColumnType("bigint");

                    b.Property<string>("Pasport_seria")
                        .HasColumnType("text");

                    b.Property<string>("Pinfl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsertType")
                        .HasColumnType("integer");

                    b.Property<bool>("active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("birthday")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("create_date")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("eng_lang")
                        .HasColumnType("integer");

                    b.Property<string>("firstname")
                        .HasColumnType("text");

                    b.Property<string>("lastname")
                        .HasColumnType("text");

                    b.Property<int>("other_lang")
                        .HasColumnType("integer");

                    b.Property<string>("phone_number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("rus_lang")
                        .HasColumnType("integer");

                    b.Property<int>("tajribasi")
                        .HasColumnType("integer");

                    b.Property<string>("user_email")
                        .HasColumnType("text");

                    b.Property<string>("user_fio")
                        .HasColumnType("text");

                    b.Property<string>("user_level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("user_login")
                        .HasColumnType("text");

                    b.Property<string>("user_password")
                        .HasColumnType("text");

                    b.Property<int>("user_typeId")
                        .HasColumnType("integer");

                    b.Property<string>("user_type_name")
                        .HasColumnType("text");

                    b.Property<int?>("user_workplace")
                        .HasColumnType("integer");

                    b.Property<int>("uzb_lang")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Emaktab.Models.Blog", b =>
                {
                    b.HasOne("Emaktab.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("create_userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emaktab.Models.Category", b =>
                {
                    b.HasOne("Emaktab.Models.Category", "ParentCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("Emaktab.Models.Document100", b =>
                {
                    b.HasOne("Emaktab.Models.Category", "Category")
                        .WithMany("Documents")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Emaktab.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Emaktab.Models.Category", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
